### ISSUE TITLE
Website revamp checklist

### ISSUE THREAD

**Issue by cgay** [dylan-lang/website#141]
I need a place to put a checklist of things I want to do before I consider my current "revamp" of the website to be complete. This is that place.

- [x] Redo the front page in the style described by Jost Grant. Quoth he...
    * Also, think frontpage ideally would be more of a 'pitch' of what OD is, links to various social media places (github org, here, etc), and like download link / setup instructions, etc
    * I think there's a tendency in / on technically aimed sites to to try to introduce people into concepts and/or documentation asap -- but really, what you're doing is trying to retain attention and interest first and foremost. 
    * I think when you're looking into a new language (I know this from my own experience when I was younger), there's a lot of social aspects to the presentation that can easily just put it into 'disqualifying' territory because people are fickle and expect "enough familiarity" that it's not so scary or 'hard' feeling and/or the tagline / ethos wasn't pervasive enough. There's obviously a LOT more than that, but even little things like that really do matter. Namely, because there's so much competition out there with a LOT more word-of-mouth / social capital to play with
- [x] Adjust URLs on docs.opendylan.org machine
    - [x] / is main site, including /tour, /hacker-guide, etc.
    - [x] /books/ for dpg and drm
    - [x] /package/foo/ for packages
    - [x] /downloads/ migrated over from opendylan.org
- [x] Repoint www.opendylan.org and opendylan.org's address records to my machine. It'll be easier for me to manage the playground and website in one place. Maybe abeaumont would like to turn down the current opendylan.org machine?
- [x] Run `make linkcheck` and correct the errors.
- [x] Deploy dpg changes automatically in update.sh
- [ ] Get plantuml extension working again.
- [x] Link to History page from the All Documentation page.
- [x] Make the Playground accessible from the site again.
- [x] Add some redirects from old URLs. e.g. /documentation/library-reference/ to /library-reference/

**Comment by cgay** [comment]
Welp.  I'm revamping the revamp, but I'll leave this bug open to make sure the rerevamp has them all covered (or there was a conscious decision to not do them).

**Comment by fraya** [comment]
I'm not using 'Plantuml' in my test module since UML (and PlantUML) don't fit with OD model. It does not allow '<' in class names. The class diagram is not useful neither. So I prefer 'graphviz' to 'Plantuml'

**Comment by cgay** [comment]
Done.
